# Generated by Django 3.0.4 on 2020-03-25 05:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CDA', '0002_maintitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Des',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintitle',
            name='name',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
