# Generated by Django 3.0.4 on 2020-03-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDA', '0003_auto_20200325_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmenubar',
            name='font_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
