# Generated by Django 3.0.4 on 2020-03-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CDA', '0004_addmenubar_font_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Overview',
        ),
    ]
